---
title: "03_preprocess_data"
author: "Jae Yeon Kim"
date: "`r Sys.Date()`"
output: html_document
---

# Import packages and files 

## Packages

```{r}
pacman::p_load(data.table, # fast data manipulation
               tidyverse, # tidyverse 
               ggpubr, # arranging ggplots   
               ggthemes, # fancy ggplot themes
               here, # reproducibility 
               maps, # US city data
               openintro, # revert state name abbreviations to their original forms 
               stringr, # easy regular expression
               lubridate, # easy time var manipulation
               forcats, # reverse factor order 
               patchwork, # easy ggarrange
               ggsci, # pubs 
               ggrepel, # annotate ggplot   
               glue, # string + object 
               purrr) # functional programming 

devtools::install_github("jaeyk/tidytweetjson")
library(tidytweetjson)

# for publication-friendly theme 
theme_set(theme_pubr())

# Custom functions
file.list <- glue("{here('functions')}/{ 
     list.files(here('functions'))}")

purrr::walk(file.list, source)
```

## Files 

- 5,050,042 obs 

```{r eval = FALSE}
parsed <- readRDS(here("processed_data", "parsed.rds"))
```

# Wrangle 

## Filter

- Filtered if location field is empty or NA: 3,734,756 obs (73% of the original data)
- I did not use country_code field as it is mostly filled with NAs (97%).

```{r eval = FALSE}
sum(is.na(parsed$country_code))/nrow(parsed)
filtered <- parsed %>%
    filter(!(location == "" | is.na(location)))
```

## Select 

```{r eval = FALSE}
# Select columns 
selected <- filtered %>% 
    select(created_at, full_text, location) 
```

## Mutate 

### Location 

- 37% of the Tweets (1,394,468) were created by the users located in the US.

```{r eval = FALSE}
# Add two columns
# US: located in the US identified by the names of the US states and cities 
# non_US: located not in the US identified by the names of the non-US countries 
df <- add_US_location(selected)
df <- subset(df, US_location == 1)
# nrow(df)/nrow(selected)
```

### Text 

```{r eval = FALSE}
# Create new columns 
df <- df %>%
    mutate(full_text = str_to_lower(full_text),
           wuhan = as.numeric(str_detect(full_text, "wuhan")),
           asian = as.numeric(str_detect(full_text, "asia|asian")),
           chinese = as.numeric(str_detect(full_text, "china|chinese")),
           trump = as.numeric(str_detect(full_text, "trump")),
           chinese_virus = as.numeric(str_detect(full_text, "chinese flu|chineseflu|chinese virus|chinesevirus")),
           kung_flu = as.numeric(str_detect(full_text, "kung flu|kungflu")), 
           wuhan_virus = as.numeric(str_detect(full_text, "wuhan virus|wuhanvirus")),
           anti_racism = as.numeric(str_detect(full_text, "antiracism|antiasian|stophate|acttochange|stopaapihate|stophatecrimes|racism|racist|hatecrime")),
           racism = ifelse(chinese_virus == 1 | kung_flu == 1 | wuhan_virus == 1, 1, 0)
           )
           
```

### Date

```{r eval = FALSE}
df <- tidytweetjson::add_date(df)
#df[1:10,] %>% select(created_at, date)

fwrite(df, here("processed_data", "US_tweets.csv"))
```

```{r}
df <- fread(here("processed_data", "US_tweets.csv"))

df <- data.frame(df)
```

# Explore 

## Group by 

```{r}
twitter <- bind_rows(
    mutate(add_normalized(df, chinese_virus), Terms = "Chinese virus"),
    mutate(add_normalized(df, kung_flu), Terms = "Kung flu"),
    mutate(add_normalized(df, wuhan_virus), Terms = "Wuhan virus"),
    mutate(add_normalized(df, anti_racism), Terms = "Anti-racism")
)
```

## Pivot 

```{r}
twitter <- twitter %>%
    filter(Terms != "Anti-racism") %>%
    pivot_wider(names_from =  Terms,
                values_from = rescaled,
                values_fill = 0)

twitter$Index <- (twitter$`Chinese virus` +
  twitter$`Kung flu` + twitter$`Wuhan virus`)/3

twitter <- twitter %>%
  pivot_longer(matches("virus|flu|Index"),
               names_to = "Terms", 
               values_to = "rescaled")
```

```{r}
twitter_plot <- twitter %>%
    ggplot(aes(x = as.Date(date), y = rescaled)) +
        geom_line(alpha = 0.3) +
        geom_point(shape = 21, 
                   color = "black", 
                   fill = "#69b3a2") +
        labs(x = "Date",
             y = "Count",
             title = "Tweets on COVID-19 (in the US)",
             subtitle = "Normalized to a 0-100 range") +
        geom_vline(xintercept = as.Date(c("2020-03-16")),
               linetype = "dashed",
               color = "blue") +
        facet_wrap(~Terms)

twitter_plot 
ggsave(here("outputs", "desc_plot.png"), height = 10, width = 10)
```

# Export 

```{r}
fwrite(df, here("processed_data", "text_ready.csv"))
```